# Generated by Django 6.0 on 2026-01-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ecommerce', '0001_initial'), ('ecommerce', '0002_alter_productmodel_product_dimensions')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('seller', models.TextField()),
                ('color', models.TextField()),
                ('product_dimensions', models.TextField(null=True)),
            ],
        ),
    ]
