# Generated by Django 6.0 on 2026-01-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_productmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='publish_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
